services:
  _defaults:
    public: true

  cdigruttola.sendcloudapi.module:
    class: Sendcloudapi
    factory: [ 'Module', 'getInstanceByName' ]
    public: false
    arguments:
      - 'sendcloudapi'
